const express = require('express');
const router = express.Router();
const db = require('../config/db');
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');
const cloudinary = require('cloudinary').v2;

// 1. Authenticate with Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

// 2. Configure Multer to upload to a specific Cloudinary folder
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: 'jcbose_complaints', // Creates a neat folder in your Cloudinary account
    allowed_formats: ['jpg', 'png', 'jpeg', 'webp']
  }
});
const upload = multer({ storage: storage });

// 3. THE POST ROUTE
// 'photos' must match the field name appended in your frontend FormData
router.post('/', upload.array('photos', 5), async (req, res) => {
  try {
    const { enrollment, title, department, category, priority, building, room, description } = req.body;
    
    // Extract the secure URLs generated by Cloudinary
    const photoUrls = req.files ? req.files.map(file => file.path) : [];

    const query = `INSERT INTO complaints 
      (student_enrollment, title, department, category, priority, building, room_no, description, photos) 
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`;
    
    // Save the array of Cloudinary URLs as a JSON string in MySQL
    const [result] = await db.execute(query, [
      enrollment, title, department, category, priority, building, room, description, JSON.stringify(photoUrls)
    ]);

    res.status(201).json({ success: true, id: result.insertId });
  } catch (error) {
    console.error('❌ Cloudinary Upload Error:', error);
    res.status(500).json({ success: false, message: "Server error during upload" });
  }
});



// ── GET route to fetch complaints for a specific student ──
router.get('/student/:enrollment', async (req, res) => {
    try {
        const { enrollment } = req.params;

        // Ask MySQL for all complaints belonging to this student, sorted by newest first
        const [complaints] = await db.execute(
            'SELECT * FROM complaints WHERE student_enrollment = ? ORDER BY created_at DESC', 
            [enrollment]
        );

        res.status(200).json({ success: true, complaints: complaints });
        
    } catch (error) {
        console.error('❌ Database error:', error);
        res.status(500).json({ success: false, message: 'Server error while fetching complaints.' });
    }
});

// ── GET COMPLAINTS BY DEPARTMENT (For HOD Dashboard) ──
router.get('/department/:dept', async (req, res) => {
    try {
        const { dept } = req.params;
        
        // This query JOINS the complaints table with the students table 
        // so the HOD can see the actual name and year of the student!
        const query = `
            SELECT c.*, s.full_name as studentName, s.study_year as studentYear
            FROM complaints c
            LEFT JOIN students s ON c.student_enrollment = s.enrollment_no
            WHERE c.department = ?
            ORDER BY c.created_at DESC
        `;
        
        const [complaints] = await db.execute(query, [dept]);
        res.status(200).json({ success: true, complaints });
    } catch (error) {
        console.error('❌ Database error:', error);
        res.status(500).json({ success: false, message: 'Server error fetching complaints.' });
    }
});

// ── UPDATE COMPLAINT STATUS OR REMARK (For HOD Dashboard) ──
router.put('/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const { status, remark } = req.body;

        if (status) {
            await db.execute('UPDATE complaints SET status = ? WHERE id = ?', [status, id]);
        }
        if (remark) {
            await db.execute('UPDATE complaints SET remark = ? WHERE id = ?', [remark, id]);
        }

        res.status(200).json({ success: true, message: 'Complaint updated successfully!' });
    } catch (error) {
        console.error('❌ Database error:', error);
        res.status(500).json({ success: false, message: 'Server error updating complaint.' });
    }
});

module.exports = router;